Repository Leukocyte-Lab/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#169 feat/gaint access for system ota
  charts/agh3/templates/captain/captain-clusterrole.yml
  charts/agh3/templates/captain/captain-clusterrolebinding.yml
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/captain/captain-sa.yaml
Labels: enhancement, Review effort [1-5]: 2

#170 feat: Use liveness probe to perform health check on endpoints.
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/controller/controller-deployment.yml
Labels: enhancement, Review effort [1-5]: 2

#171 build: Release chart/agh3 `v3.5.0`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#173 build: Release chart/agh3 `v3.5.1`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#174 build: Release chart/agh3 `v3.5.2`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#175 build: Release chart/agh3 `v3.5.3`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#176 build: Release chart/agh3 `v3.5.4`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#177 build: Release chart/agh3 `v3.5.5`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#178 build: Release chart/agh3 `v3.5.6`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1
