Repository Leukocyte-Lab/helm-charts, pull requests merged in 2024-07, with the labels that each got.

#179 build: Release chart/agh3 `v3.5.7`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#180 build: Release chart/agh3 `v3.5.8`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#181 build: Release chart/agh3 `v3.5.9`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#182 build: Release chart/agh3 `v3.5.10`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#183 build: Release chart/agh3 `v3.5.11`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#184 build: Release chart/agh3 `v3.5.12`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#185 build: Release chart/agh3 `v3.5.13`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#186 ci: Create workflow to auto update release channel after PR merged.
  .github/workflows/agh3-update-develop-release-channel.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#190 feat/add oidc support
  charts/agh3/README.md
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/captain/captain-oidc-secret.yml
  charts/agh3/templates/validations/index.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#191 chore: Modify default postfix vaules.
  charts/agh3/README.md
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#192 feat/add playground chart
  .github/workflows/agh3-playground-publish.yaml
  .github/workflows/agh3-playground-release.yml
  .github/workflows/agh3-playground-test.yml
  charts/playground/Chart.lock
  charts/playground/Chart.yaml
  charts/playground/README.md
  charts/playground/templates/_helpers.tpl
  charts/playground/templates/_utils.tpl
  charts/playground/templates/agh-playground-ingressroute.yml
  charts/playground/templates/playground-deployment.yml
  charts/playground/templates/playground-service.yml
  charts/playground/templates/validations/_required.tpl
  charts/playground/templates/validations/index.yaml
  charts/playground/values.yaml
Labels: enhancement, tests, Review effort [1-5]: 4, configuration changes

#193 build: Release chart/agh3 `v3.6.0`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#194 build: Release chart/agh3 `v3.6.1`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#195 fix/potential confliction on rbac resources
  charts/agh3/templates/_helpers.tpl
  charts/agh3/templates/captain/captain-clusterrole.yml
  charts/agh3/templates/captain/captain-clusterrolebinding.yml
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/captain/captain-sa.yaml
  charts/agh3/templates/controller/controller-clusterrole.yml
  charts/agh3/templates/controller/controller-clusterrolebinding.yml
  charts/agh3/templates/controller/controller-deployment.yml
  charts/agh3/templates/controller/controller-sa.yml
  charts/agh3/values.yaml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#196 fix: OIDC secretRefs should be optional.
  charts/agh3/templates/captain/captain-deployment.yml
Labels: Review effort [1-5]: 1, Bug fix

#197 build: Release chart/agh3 `v3.6.2`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1
