Repository Leukocyte-Lab/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#198 build: Release chart/agh3 `v3.6.3`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#201 build: Release chart/agh3 `v3.6.4`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#203 build: Release chart/agh3 `v3.6.5`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#204 Fix Auto Release AGH3
  .github/workflows/agh3-auto-release.yaml
Labels: enhancement, Review effort [1-5]: 1, Bug fix

#205 Revert "build: Release chart/agh3 `v3.6.5`"
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#206 build: Release chart/agh3 `v3.6.5`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#208 feat/add global proxy
  charts/agh3/templates/_helpers.tpl
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/controller/controller-deployment.yml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes
