Repository Leukocyte-Lab/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#210 build: Release chart/agh3 `v3.7.0`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#211 fix: Should respect proxy enabled value.
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/templates/controller/controller-deployment.yml
Labels: Review effort [1-5]: 1, Bug fix

#212 build: Release chart/agh3 `v3.7.1`
  charts/agh3/Chart.yaml
Labels: enhancement, Review effort [1-5]: 1

#213 build: Release chart/agh3 `v3.7.2`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#215 build: Release chart/agh3 `v3.7.4`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#216 build: Release chart/agh3 `v3.7.5`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#217 build: Release chart/agh3 `v3.7.6`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1, other

#219 feat/playground/add firebase secrets
  .github/workflows/agh3-playground-test.yml
  charts/playground/templates/agh-playground-ingressroute.yml
  charts/playground/templates/firebase-secret.yml
  charts/playground/templates/playground-deployment.yml
  charts/playground/values.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#220 feat: add redis
  .helmignore
  charts/agh3/Chart.lock
  charts/agh3/Chart.yaml
  charts/agh3/README.md
  charts/agh3/templates/_helpers.tpl
  charts/agh3/templates/base/redis-secret.yml
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#221 build: Release chart/agh3-playground `v1.0.0`
  charts/playground/Chart.yaml
  charts/playground/values.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#222 build: Release chart/agh3-playground `v1.0.1`
  charts/playground/Chart.yaml
  charts/playground/values.yaml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#223 feat: add keygen url env
  charts/agh3/templates/captain/captain-deployment.yml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#226 ci: update postfix release ci
  .github/workflows/postfix.yml
Labels: enhancement, Review effort [1-5]: 2

#228 build: Release chart/agh3 `v3.7.9`
  charts/agh3/Chart.yaml
Labels: enhancement, Review effort [1-5]: 1
