Repository Leukocyte-Lab/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#229 build: Release chart/agh3-playground `v1.1.0`
  charts/playground/Chart.yaml
  charts/playground/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#230 build: Change redis to standalone mode.
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#231 build: Release chart/agh3-playground `v1.2.0`
  charts/playground/Chart.yaml
  charts/playground/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#232 build(deps): Update dependencies charts
  charts/agh3/Chart.lock
  charts/agh3/Chart.yaml
  charts/agh3/templates/report/report-deployment.yml
  charts/agh3/templates/report/report-service.yml
  charts/agh3/values.yaml
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#233 build: Release chart/agh3 `v3.8.0`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#234 Revert "build(deps): Update dependencies charts"
  charts/agh3/Chart.lock
  charts/agh3/Chart.yaml
Labels: Bug fix, Review effort [1-5]: 2

#235 build: Release chart/agh3-playground `v1.2.1`
  charts/playground/Chart.yaml
Labels: enhancement, Review effort [1-5]: 1

#236 build: Release chart/agh3 `v3.8.1`
  charts/agh3/Chart.yaml
Labels: enhancement, Review effort [1-5]: 1

#237 build: Release chart/agh3 `v3.8.2`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#239 build: Release chart/agh3 `v3.8.3`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#240 build: Release chart/agh3 `v3.8.4`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#241 build: Release chart/agh3 `v3.8.5`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#242 build: Release chart/agh3 `v3.8.6`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#243 build: Release chart/agh3 `v3.8.7`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#244 build: Release chart/agh3 `v3.8.8`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#245 build: Release chart/agh3 `v3.8.9`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#247 build: Release chart/agh3 `v3.8.10`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#256 feat: enable minio webhook
  charts/agh3/templates/minio/agh-minio-cm.yml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#259 build: Release chart/agh3 `v3.9.0`
  charts/agh3/Chart.yaml
  charts/agh3/values.yaml
Labels: enhancement, Review effort [1-5]: 1
